<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOOIFngy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOOIFngy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOOIFngy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOOIFngy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOOIFngy\App_KernelDevDebugContainer([
    'container.build_hash' => 'OOIFngy',
    'container.build_id' => 'dbf6ad5e',
    'container.build_time' => 1585223073,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOOIFngy');
