<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8ckqfOY\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8ckqfOY/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container8ckqfOY.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container8ckqfOY\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \Container8ckqfOY\App_KernelTestDebugContainer([
    'container.build_hash' => '8ckqfOY',
    'container.build_id' => 'f2c64e01',
    'container.build_time' => 1586189560,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8ckqfOY');
