<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'admin.formation.index' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminFormationController::index'], [], [['text', '/admin']], [], []],
    'admin.formation.edit' => [['id'], ['_controller' => 'App\\Controller\\Admin\\AdminFormationController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/formation']], [], []],
    'admin.formation.delete' => [['id'], ['_controller' => 'App\\Controller\\Admin\\AdminFormationController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/formation']], [], []],
    'categorie.route' => [[], ['_controller' => 'App\\Controller\\CategorieController::index'], [], [['text', '/categories']], [], []],
    'categorie.show' => [['slug', 'id'], ['_controller' => 'App\\Controller\\CategorieController::show'], ['slug' => '[a-z0-9\\-]*'], [['variable', '-', '[^/]++', 'id', true], ['variable', '/', '[a-z0-9\\-]*', 'slug', true], ['text', '/categorie']], [], []],
    'formation.route' => [[], ['_controller' => 'App\\Controller\\FormationController::index'], [], [['text', '/formations']], [], []],
    'formation.show' => [['slug', 'id'], ['_controller' => 'App\\Controller\\FormationController::show'], ['slug' => '[a-z0-9\\-]*'], [['variable', '-', '[^/]++', 'id', true], ['variable', '/', '[a-z0-9\\-]*', 'slug', true], ['text', '/formations']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'informations' => [[], ['_controller' => 'App\\Controller\\InformationsController::index'], [], [['text', '/informations']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'logout' => [[], [], [], [['text', '/logout']], [], []],
];
