<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSbxp5cL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSbxp5cL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSbxp5cL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSbxp5cL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSbxp5cL\App_KernelDevDebugContainer([
    'container.build_hash' => 'Sbxp5cL',
    'container.build_id' => '4efe1526',
    'container.build_time' => 1590485583,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSbxp5cL');
