<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXh25VK8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXh25VK8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXh25VK8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXh25VK8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXh25VK8\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xh25VK8',
    'container.build_id' => '7dea0b5a',
    'container.build_time' => 1585302757,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXh25VK8');
